name: music_reading_trainir
description: A Flutter piano sight-reading training application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  stacked: ^3.4.0
  permission_handler: ^11.0.0
  pitch_detector_dart: ^0.0.7
  record: ^5.1.2
  just_audio: ^0.10.5
  path_provider: ^2.1.5

dependency_overrides:
  record_linux: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/soundfont/
